version: '3.8'

services:
  # server:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   restart: on-failure

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=pokemon_store_luxor
      - POSTGRES_USER=alexander
      - POSTGRES_PASSWORD=admin1234
    ports:
      - 5455:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=alexander@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
