/* eslint-disable */

export default () => ({
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: './src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  moduleNameMapper: {
    '@health/(.*)': '<rootDir>/health/$1',
    '@services/(.*)': '<rootDir>/services/$1',
    '@utils/(.*)': '<rootDir>/lib/utils/$1',
    '@config': '<rootDir>/lib/config/index.ts',
    '@core/(.*)': '<rootDir>/core/$1',
    '@logger': '<rootDir>/lib/logger/index.ts',
    '@helpers/(.*)': '<rootDir>/lib/helpers/$1',
    '@constants/(.*)': '<rootDir>/lib/constants/$1',
    '@db/(.*)': '<rootDir>/lib/db/$1',
    '@dto/(.*)': '<rootDir>/lib/dto/$1',
    '@imgix/(.*)': '<rootDir>/lib/imgix/$1',
    '@enums/(.*)': '<rootDir>/lib/enums/$1',
    '@interfaces': '<rootDir>/lib/interfaces/$1',
    '@schemas/(.*)': '<rootDir>/schemas/$1',
    '@resolvers/(.*)': '<rootDir>/resolvers/$1',
    '@controllers/(.*)': '<rootDir>/controllers/$1',
    '@routes/(.*)': '<rootDir>/routes/$1',
    "@middlewares/(.*)": '<rootDir>/middlewares/$1',
    '@external-services/(.*)': '<rootDir>/external-services/$1',
    '@magentoLib/(.*)': '<rootDir>/lib/magento/$1',
    '@unleashLib/(.*)': '<rootDir>/lib/unleash/$1',
    '@@loaders': '<rootDir>/lib/loaders/$1',
    "@ms-redis/(.*)": '<rootDir>/lib/redis/$1',
    "@ms-axios/(.*)": '<rootDir>/lib/axios/$1',
  },
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/test/',
    '^.*\\.module\\.[jt]s?$',
    '^.*\\.schema\\.[jt]s?$',
    '^.*\\.interface\\.[jt]s?$',
    '^.*\\.enum\\.[jt]s?$',
    '^.*\\.constant\\.[jt]s?$',
    '^.*\\.dto\\.[jt]s?$',
    '/src/lib/config/',
    '/src/lib/db/',
    '/src/lib/loaders/',
  ],
  setupFilesAfterEnv: ['../setup-jest.ts', '<rootDir>/lib/db/prisma-client.mock.ts'],
});
